################################################################################
################################################################################
#This is a code to simulate the discrete-time Beverton-Holt model for population #growth and plot dynamics along with predicted solution
################################################################################
rm(list=ls()) # Clear workspace
################################################################################
# Model parameters
lambda0=2 #intrinsic growth rate of the population
alpha=0.01 #intra-specific competeion coefficient
#Initial conditions
N0=10 # we start with N0 individuals
#Total time for which we simulate dynamics
t_max=1000
#Arrays to store population
N=array() #create an array that stores population density 
N[1]=N0   #set the value of the first element to N0
###############################################################################
#Loop to simulate dynamics
for(t in 1:(t_max-1))#go through time
{
  #calculate the density at time t+1 from the density at time t
  N[(t+1)]=N[(t)]*lambda0/(1+alpha*N[(t)]) 
}
###############################################################################
#Plot dynamics of the Beverton-Holt model
plot(1:t_max,N,type="l",xlab="Generations",ylab="Population density")
#The equilibrium of this  model as you have calculated is 
#(lambda0-1)/alpha
abline(h=(lambda0-1)/alpha)

###############################################################################
#Read the data generated by the individual-based model
homedir=getwd()
setwd(homedir)

output=read.table("output.txt",header=T)

# for(r in unique(output$r))
# {
#   plot(1:t_max,N,col="red",type="l",ylim=c(0,150),xlim=c(0,1000),lwd=2, xlab="Time",ylab="Population Density")
#   for(x in 0:99)
#   {
#     lines(output$t[output$r==r & output$x==x],output$N[output$r==r & output$x==x],lwd=1)
#   }
#   
# }
# 
# legend("topright",col=c("red","black"),c("Deterministic Beverton-Holt model","Individual-based model"),lty=c(1,1),bty="n")
# 
# 
# for(r in unique(output$r))
# {
#   plot(1:t_max,N,col="red",type="l",ylim=c(0,1),xlim=c(0,2000),lwd=2, xlab="Time",ylab="Population Density")
#   for(x in 0:99)
#   {
#     lines(output$t[output$r==r & output$x==x],output$measured_dispersal[output$r==r & output$x==x],lwd=1)
#   }
#   
# }

plot(0,0,xlim=c(0,2000),ylim=c(0,1),type="n")
for(r in unique(output$r))
{
lines(unique(output$t[output$r==r]),apply(matrix(output$measured_dispersal[output$r==r],100),2,mean),type="l")
}

